### ISSUE TITLE
Cannot build the module successfully

### ISSUE THREAD

**Issue by zengbowenbit** [BenNewton/wireless-point-to-point#1]
I put the _wireless-point-to-point_ folder in my _ns-3/src_ folder and build it, but I am faced with some mistakes as follows. Could you give me some hints about it?

![image](https://user-images.githubusercontent.com/31918620/43304062-152fdce0-91a5-11e8-8ac3-61d50d7b9a97.png)

**Comment by BenNewton** [comment]
What version of ns-3?

**Comment by zengbowenbit** [comment]
The ns-3 version has been updated to 3.28.
I try the 3.26 version and it works :)

**Comment by BenNewton** [comment]
I wonder if there were changes made since 3.26 that cause it not to work?
